#ifdef ___LINKER_INFO
; File: "syntax.c", produced by Gambit v4.8.9
(
408009
(C)
"bin:jazz.platform.syntax"
(("bin:jazz.platform.syntax"))
(
"apply"
"begin"
"bin:jazz.platform.syntax"
"c-external"
"definition"
"foundation.dialect"
"jazz"
"jazz.platform.syntax"
"jazz.platform.syntax:platform-external"
"lambda"
"params"
"public"
"quote"
"rest"
"s-name"
"set!"
"signature"
"trace-platform"
"trace-platform?"
"when"
)
(
)
(
"bin:jazz.platform.syntax#"
"jazz.platform.syntax:tracable?"
)
(
)
(
"##interaction-cte"
"##make-macro-descr"
"##top-cte-add-macro!"
"car"
"cdr"
"jazz:load-unit"
"jazz:register-macro"
"jazz:register-module"
"string->symbol"
"string-append"
"symbol->string"
)
 ()
)
#else
#define ___VERSION 408009
#define ___MODULE_NAME "bin:jazz.platform.syntax"
#define ___LINKER_ID ___LNK_bin_3a_jazz_2e_platform_2e_syntax
#define ___MH_PROC ___H_bin_3a_jazz_2e_platform_2e_syntax
#define ___SCRIPT_LINE 0
#define ___SYMCOUNT 20
#define ___GLOCOUNT 13
#define ___SUPCOUNT 2
#define ___CNSCOUNT 8
#define ___SUBCOUNT 55
#define ___LBLCOUNT 26
#define ___MODDESCR ___REF_SUB(54)
#include "gambit.h"

___NEED_SYM(___S_apply)
___NEED_SYM(___S_begin)
___NEED_SYM(___S_bin_3a_jazz_2e_platform_2e_syntax)
___NEED_SYM(___S_c_2d_external)
___NEED_SYM(___S_definition)
___NEED_SYM(___S_foundation_2e_dialect)
___NEED_SYM(___S_jazz)
___NEED_SYM(___S_jazz_2e_platform_2e_syntax)
___NEED_SYM(___S_jazz_2e_platform_2e_syntax_3a_platform_2d_external)
___NEED_SYM(___S_lambda)
___NEED_SYM(___S_params)
___NEED_SYM(___S_public)
___NEED_SYM(___S_quote)
___NEED_SYM(___S_rest)
___NEED_SYM(___S_s_2d_name)
___NEED_SYM(___S_set_21_)
___NEED_SYM(___S_signature)
___NEED_SYM(___S_trace_2d_platform)
___NEED_SYM(___S_trace_2d_platform_3f_)
___NEED_SYM(___S_when)

___NEED_GLO(___G__23__23_interaction_2d_cte)
___NEED_GLO(___G__23__23_make_2d_macro_2d_descr)
___NEED_GLO(___G__23__23_top_2d_cte_2d_add_2d_macro_21_)
___NEED_GLO(___G_bin_3a_jazz_2e_platform_2e_syntax_23_)
___NEED_GLO(___G_car)
___NEED_GLO(___G_cdr)
___NEED_GLO(___G_jazz_2e_platform_2e_syntax_3a_tracable_3f_)
___NEED_GLO(___G_jazz_3a_load_2d_unit)
___NEED_GLO(___G_jazz_3a_register_2d_macro)
___NEED_GLO(___G_jazz_3a_register_2d_module)
___NEED_GLO(___G_string_2d__3e_symbol)
___NEED_GLO(___G_string_2d_append)
___NEED_GLO(___G_symbol_2d__3e_string)

___BEGIN_SYM
___DEF_SYM(0,___S_apply,"apply")
___DEF_SYM(1,___S_begin,"begin")
___DEF_SYM(2,___S_bin_3a_jazz_2e_platform_2e_syntax,"bin:jazz.platform.syntax")
___DEF_SYM(3,___S_c_2d_external,"c-external")
___DEF_SYM(4,___S_definition,"definition")
___DEF_SYM(5,___S_foundation_2e_dialect,"foundation.dialect")
___DEF_SYM(6,___S_jazz,"jazz")
___DEF_SYM(7,___S_jazz_2e_platform_2e_syntax,"jazz.platform.syntax")
___DEF_SYM(8,___S_jazz_2e_platform_2e_syntax_3a_platform_2d_external,"jazz.platform.syntax:platform-external")

___DEF_SYM(9,___S_lambda,"lambda")
___DEF_SYM(10,___S_params,"params")
___DEF_SYM(11,___S_public,"public")
___DEF_SYM(12,___S_quote,"quote")
___DEF_SYM(13,___S_rest,"rest")
___DEF_SYM(14,___S_s_2d_name,"s-name")
___DEF_SYM(15,___S_set_21_,"set!")
___DEF_SYM(16,___S_signature,"signature")
___DEF_SYM(17,___S_trace_2d_platform,"trace-platform")
___DEF_SYM(18,___S_trace_2d_platform_3f_,"trace-platform?")
___DEF_SYM(19,___S_when,"when")
___END_SYM

#define ___SYM_apply ___SYM(0,___S_apply)
#define ___SYM_begin ___SYM(1,___S_begin)
#define ___SYM_bin_3a_jazz_2e_platform_2e_syntax ___SYM(2,___S_bin_3a_jazz_2e_platform_2e_syntax)
#define ___SYM_c_2d_external ___SYM(3,___S_c_2d_external)
#define ___SYM_definition ___SYM(4,___S_definition)
#define ___SYM_foundation_2e_dialect ___SYM(5,___S_foundation_2e_dialect)
#define ___SYM_jazz ___SYM(6,___S_jazz)
#define ___SYM_jazz_2e_platform_2e_syntax ___SYM(7,___S_jazz_2e_platform_2e_syntax)
#define ___SYM_jazz_2e_platform_2e_syntax_3a_platform_2d_external ___SYM(8,___S_jazz_2e_platform_2e_syntax_3a_platform_2d_external)
#define ___SYM_lambda ___SYM(9,___S_lambda)
#define ___SYM_params ___SYM(10,___S_params)
#define ___SYM_public ___SYM(11,___S_public)
#define ___SYM_quote ___SYM(12,___S_quote)
#define ___SYM_rest ___SYM(13,___S_rest)
#define ___SYM_s_2d_name ___SYM(14,___S_s_2d_name)
#define ___SYM_set_21_ ___SYM(15,___S_set_21_)
#define ___SYM_signature ___SYM(16,___S_signature)
#define ___SYM_trace_2d_platform ___SYM(17,___S_trace_2d_platform)
#define ___SYM_trace_2d_platform_3f_ ___SYM(18,___S_trace_2d_platform_3f_)
#define ___SYM_when ___SYM(19,___S_when)

___BEGIN_GLO
___DEF_GLO(0,"bin:jazz.platform.syntax#")
___DEF_GLO(1,"jazz.platform.syntax:tracable?")
___DEF_GLO(2,"##interaction-cte")
___DEF_GLO(3,"##make-macro-descr")
___DEF_GLO(4,"##top-cte-add-macro!")
___DEF_GLO(5,"car")
___DEF_GLO(6,"cdr")
___DEF_GLO(7,"jazz:load-unit")
___DEF_GLO(8,"jazz:register-macro")
___DEF_GLO(9,"jazz:register-module")
___DEF_GLO(10,"string->symbol")
___DEF_GLO(11,"string-append")
___DEF_GLO(12,"symbol->string")
___END_GLO

#define ___GLO_bin_3a_jazz_2e_platform_2e_syntax_23_ ___GLO(0,___G_bin_3a_jazz_2e_platform_2e_syntax_23_)
#define ___PRM_bin_3a_jazz_2e_platform_2e_syntax_23_ ___PRM(0,___G_bin_3a_jazz_2e_platform_2e_syntax_23_)
#define ___GLO_jazz_2e_platform_2e_syntax_3a_tracable_3f_ ___GLO(1,___G_jazz_2e_platform_2e_syntax_3a_tracable_3f_)
#define ___PRM_jazz_2e_platform_2e_syntax_3a_tracable_3f_ ___PRM(1,___G_jazz_2e_platform_2e_syntax_3a_tracable_3f_)
#define ___GLO__23__23_interaction_2d_cte ___GLO(2,___G__23__23_interaction_2d_cte)
#define ___PRM__23__23_interaction_2d_cte ___PRM(2,___G__23__23_interaction_2d_cte)
#define ___GLO__23__23_make_2d_macro_2d_descr ___GLO(3,___G__23__23_make_2d_macro_2d_descr)
#define ___PRM__23__23_make_2d_macro_2d_descr ___PRM(3,___G__23__23_make_2d_macro_2d_descr)
#define ___GLO__23__23_top_2d_cte_2d_add_2d_macro_21_ ___GLO(4,___G__23__23_top_2d_cte_2d_add_2d_macro_21_)
#define ___PRM__23__23_top_2d_cte_2d_add_2d_macro_21_ ___PRM(4,___G__23__23_top_2d_cte_2d_add_2d_macro_21_)
#define ___GLO_car ___GLO(5,___G_car)
#define ___PRM_car ___PRM(5,___G_car)
#define ___GLO_cdr ___GLO(6,___G_cdr)
#define ___PRM_cdr ___PRM(6,___G_cdr)
#define ___GLO_jazz_3a_load_2d_unit ___GLO(7,___G_jazz_3a_load_2d_unit)
#define ___PRM_jazz_3a_load_2d_unit ___PRM(7,___G_jazz_3a_load_2d_unit)
#define ___GLO_jazz_3a_register_2d_macro ___GLO(8,___G_jazz_3a_register_2d_macro)
#define ___PRM_jazz_3a_register_2d_macro ___PRM(8,___G_jazz_3a_register_2d_macro)
#define ___GLO_jazz_3a_register_2d_module ___GLO(9,___G_jazz_3a_register_2d_module)
#define ___PRM_jazz_3a_register_2d_module ___PRM(9,___G_jazz_3a_register_2d_module)
#define ___GLO_string_2d__3e_symbol ___GLO(10,___G_string_2d__3e_symbol)
#define ___PRM_string_2d__3e_symbol ___PRM(10,___G_string_2d__3e_symbol)
#define ___GLO_string_2d_append ___GLO(11,___G_string_2d_append)
#define ___PRM_string_2d_append ___PRM(11,___G_string_2d_append)
#define ___GLO_symbol_2d__3e_string ___GLO(12,___G_symbol_2d__3e_string)
#define ___PRM_symbol_2d__3e_string ___PRM(12,___G_symbol_2d__3e_string)

___BEGIN_CNS
 ___DEF_CNS(___REF_SYM(13,___S_rest),___REF_NUL)
,___DEF_CNS(___REF_SYM(13,___S_rest),___REF_NUL)
,___DEF_CNS(___REF_SYM(17,___S_trace_2d_platform),___REF_NUL)
,___DEF_CNS(___REF_SYM(18,___S_trace_2d_platform_3f_),___REF_NUL)
,___DEF_CNS(___REF_SYM(13,___S_rest),___REF_NUL)
,___DEF_CNS(___REF_SYM(13,___S_rest),___REF_NUL)
,___DEF_CNS(___REF_SYM(17,___S_trace_2d_platform),___REF_NUL)
,___DEF_CNS(___REF_SYM(18,___S_trace_2d_platform_3f_),___REF_NUL)
___END_CNS

___DEF_SUB_STR(___X0,9UL)
               ___STR8(36,117,110,116,114,97,99,101)
               ___STR1(100)
___DEF_SUB_VEC(___X1,2UL)
               ___VEC1(___REF_SUB(2))
               ___VEC1(___REF_SUB(53))
               ___VEC0
___DEF_SUB_VEC(___X2,25UL)
               ___VEC1(___REF_SUB(3))
               ___VEC1(___REF_SUB(5))
               ___VEC1(___REF_SUB(7))
               ___VEC1(___REF_SUB(9))
               ___VEC1(___REF_SUB(11))
               ___VEC1(___REF_SUB(13))
               ___VEC1(___REF_SUB(15))
               ___VEC1(___REF_SUB(17))
               ___VEC1(___REF_SUB(19))
               ___VEC1(___REF_SUB(21))
               ___VEC1(___REF_SUB(23))
               ___VEC1(___REF_SUB(25))
               ___VEC1(___REF_SUB(27))
               ___VEC1(___REF_SUB(29))
               ___VEC1(___REF_SUB(31))
               ___VEC1(___REF_SUB(33))
               ___VEC1(___REF_SUB(35))
               ___VEC1(___REF_SUB(37))
               ___VEC1(___REF_SUB(39))
               ___VEC1(___REF_SUB(41))
               ___VEC1(___REF_SUB(43))
               ___VEC1(___REF_SUB(45))
               ___VEC1(___REF_SUB(47))
               ___VEC1(___REF_SUB(49))
               ___VEC1(___REF_SUB(51))
               ___VEC0
___DEF_SUB_VEC(___X3,2UL)
               ___VEC1(___REF_FIX(0))
               ___VEC1(___REF_SUB(4))
               ___VEC0
___DEF_SUB_VEC(___X4,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(37))
               ___VEC0
___DEF_SUB_VEC(___X5,2UL)
               ___VEC1(___REF_FIX(1))
               ___VEC1(___REF_SUB(6))
               ___VEC0
___DEF_SUB_VEC(___X6,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(37))
               ___VEC0
___DEF_SUB_VEC(___X7,2UL)
               ___VEC1(___REF_FIX(2))
               ___VEC1(___REF_SUB(8))
               ___VEC0
___DEF_SUB_VEC(___X8,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(37))
               ___VEC0
___DEF_SUB_VEC(___X9,2UL)
               ___VEC1(___REF_FIX(3))
               ___VEC1(___REF_SUB(10))
               ___VEC0
___DEF_SUB_VEC(___X10,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(37))
               ___VEC0
___DEF_SUB_VEC(___X11,2UL)
               ___VEC1(___REF_FIX(4))
               ___VEC1(___REF_SUB(12))
               ___VEC0
___DEF_SUB_VEC(___X12,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(37))
               ___VEC0
___DEF_SUB_VEC(___X13,2UL)
               ___VEC1(___REF_FIX(5))
               ___VEC1(___REF_SUB(14))
               ___VEC0
___DEF_SUB_VEC(___X14,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X15,2UL)
               ___VEC1(___REF_FIX(6))
               ___VEC1(___REF_SUB(16))
               ___VEC0
___DEF_SUB_VEC(___X16,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X17,2UL)
               ___VEC1(___REF_FIX(7))
               ___VEC1(___REF_SUB(18))
               ___VEC0
___DEF_SUB_VEC(___X18,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X19,2UL)
               ___VEC1(___REF_FIX(8))
               ___VEC1(___REF_SUB(20))
               ___VEC0
___DEF_SUB_VEC(___X20,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X21,2UL)
               ___VEC1(___REF_FIX(9))
               ___VEC1(___REF_SUB(22))
               ___VEC0
___DEF_SUB_VEC(___X22,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X23,6UL)
               ___VEC1(___REF_FIX(10))
               ___VEC1(___REF_SUB(24))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X24,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X25,6UL)
               ___VEC1(___REF_FIX(11))
               ___VEC1(___REF_SUB(26))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X26,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X27,6UL)
               ___VEC1(___REF_FIX(12))
               ___VEC1(___REF_SUB(28))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X28,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X29,2UL)
               ___VEC1(___REF_FIX(13))
               ___VEC1(___REF_SUB(30))
               ___VEC0
___DEF_SUB_VEC(___X30,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X31,5UL)
               ___VEC1(___REF_FIX(14))
               ___VEC1(___REF_SUB(32))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X32,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X33,4UL)
               ___VEC1(___REF_FIX(15))
               ___VEC1(___REF_SUB(34))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X34,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X35,2UL)
               ___VEC1(___REF_FIX(16))
               ___VEC1(___REF_SUB(36))
               ___VEC0
___DEF_SUB_VEC(___X36,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X37,2UL)
               ___VEC1(___REF_FIX(17))
               ___VEC1(___REF_SUB(38))
               ___VEC0
___DEF_SUB_VEC(___X38,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X39,6UL)
               ___VEC1(___REF_FIX(18))
               ___VEC1(___REF_SUB(40))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X40,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X41,6UL)
               ___VEC1(___REF_FIX(19))
               ___VEC1(___REF_SUB(42))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X42,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X43,6UL)
               ___VEC1(___REF_FIX(20))
               ___VEC1(___REF_SUB(44))
               ___VEC1(___REF_FIX(163840))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X44,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X45,2UL)
               ___VEC1(___REF_FIX(21))
               ___VEC1(___REF_SUB(46))
               ___VEC0
___DEF_SUB_VEC(___X46,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X47,5UL)
               ___VEC1(___REF_FIX(22))
               ___VEC1(___REF_SUB(48))
               ___VEC1(___REF_FIX(131074))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X48,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X49,4UL)
               ___VEC1(___REF_FIX(23))
               ___VEC1(___REF_SUB(50))
               ___VEC1(___REF_FIX(98308))
               ___VEC1(___REF_FIX(65542))
               ___VEC0
___DEF_SUB_VEC(___X50,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X51,2UL)
               ___VEC1(___REF_FIX(24))
               ___VEC1(___REF_SUB(52))
               ___VEC0
___DEF_SUB_VEC(___X52,2UL)
               ___VEC1(___REF_SYM(7,___S_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_FIX(49))
               ___VEC0
___DEF_SUB_VEC(___X53,4UL)
               ___VEC1(___REF_SYM(10,___S_params))
               ___VEC1(___REF_SYM(14,___S_s_2d_name))
               ___VEC1(___REF_SYM(13,___S_rest))
               ___VEC1(___REF_SYM(16,___S_signature))
               ___VEC0
___DEF_SUB_VEC(___X54,5UL)
               ___VEC1(___REF_SYM(2,___S_bin_3a_jazz_2e_platform_2e_syntax))
               ___VEC1(___REF_PRC(1))
               ___VEC1(___REF_FIX(1))
               ___VEC1(___REF_NUL)
               ___VEC1(___REF_FAL)
               ___VEC0

___BEGIN_SUB
 ___DEF_SUB(___X0)
,___DEF_SUB(___X1)
,___DEF_SUB(___X2)
,___DEF_SUB(___X3)
,___DEF_SUB(___X4)
,___DEF_SUB(___X5)
,___DEF_SUB(___X6)
,___DEF_SUB(___X7)
,___DEF_SUB(___X8)
,___DEF_SUB(___X9)
,___DEF_SUB(___X10)
,___DEF_SUB(___X11)
,___DEF_SUB(___X12)
,___DEF_SUB(___X13)
,___DEF_SUB(___X14)
,___DEF_SUB(___X15)
,___DEF_SUB(___X16)
,___DEF_SUB(___X17)
,___DEF_SUB(___X18)
,___DEF_SUB(___X19)
,___DEF_SUB(___X20)
,___DEF_SUB(___X21)
,___DEF_SUB(___X22)
,___DEF_SUB(___X23)
,___DEF_SUB(___X24)
,___DEF_SUB(___X25)
,___DEF_SUB(___X26)
,___DEF_SUB(___X27)
,___DEF_SUB(___X28)
,___DEF_SUB(___X29)
,___DEF_SUB(___X30)
,___DEF_SUB(___X31)
,___DEF_SUB(___X32)
,___DEF_SUB(___X33)
,___DEF_SUB(___X34)
,___DEF_SUB(___X35)
,___DEF_SUB(___X36)
,___DEF_SUB(___X37)
,___DEF_SUB(___X38)
,___DEF_SUB(___X39)
,___DEF_SUB(___X40)
,___DEF_SUB(___X41)
,___DEF_SUB(___X42)
,___DEF_SUB(___X43)
,___DEF_SUB(___X44)
,___DEF_SUB(___X45)
,___DEF_SUB(___X46)
,___DEF_SUB(___X47)
,___DEF_SUB(___X48)
,___DEF_SUB(___X49)
,___DEF_SUB(___X50)
,___DEF_SUB(___X51)
,___DEF_SUB(___X52)
,___DEF_SUB(___X53)
,___DEF_SUB(___X54)
___END_SUB



#undef ___MD_ALL
#define ___MD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___MR_ALL
#define ___MR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___MW_ALL
#define ___MW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_M_COD
___BEGIN_M_HLBL
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L1_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L2_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L3_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L4_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L5_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L6_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L7_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L8_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L9_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L10_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L11_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L12_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L13_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L14_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L15_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L16_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L17_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L18_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L19_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L20_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L21_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L22_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L23_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_M_HLBL(___L24_bin_3a_jazz_2e_platform_2e_syntax_23_)
___END_M_HLBL

___BEGIN_M_SW

#undef ___PH_PROC
#define ___PH_PROC ___H_bin_3a_jazz_2e_platform_2e_syntax_23_
#undef ___PH_LBL0
#define ___PH_LBL0 1
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L1_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L2_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L3_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L4_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L5_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L6_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L7_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L8_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L9_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L10_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L11_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L12_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L13_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L14_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L15_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L16_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L17_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L18_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L19_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L20_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L21_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L22_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L23_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_P_HLBL(___L24_bin_3a_jazz_2e_platform_2e_syntax_23_)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___R0)
   ___SET_R1(___SYM_foundation_2e_dialect)
   ___ADJFP(4)
   ___POLL(1)
___DEF_SLBL(1,___L1_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R0(___LBL(2))
   ___JUMPGLOSAFE(___SET_NARGS(1),7,___G_jazz_3a_load_2d_unit)
___DEF_SLBL(2,___L2_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R1(___SYM_jazz)
   ___SET_R0(___LBL(3))
   ___JUMPGLOSAFE(___SET_NARGS(1),7,___G_jazz_3a_load_2d_unit)
___DEF_SLBL(3,___L3_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___SYM_jazz_2e_platform_2e_syntax)
   ___SET_R3(___NUL)
   ___SET_R2(___NUL)
   ___SET_R1(___SYM_public)
   ___SET_R0(___LBL(4))
   ___ADJFP(1)
   ___JUMPGLOSAFE(___SET_NARGS(4),9,___G_jazz_3a_register_2d_module)
___DEF_SLBL(4,___L4_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_GLO(1,___G_jazz_2e_platform_2e_syntax_3a_tracable_3f_,___FAL)
   ___SET_STK(1,___FAL)
   ___SET_R2(___LBL(17))
   ___SET_R3(___FAL)
   ___SET_R1(___FIX(-2L))
   ___SET_R0(___LBL(5))
   ___ADJFP(1)
   ___JUMPGLOSAFE(___SET_NARGS(4),3,___G__23__23_make_2d_macro_2d_descr)
___DEF_SLBL(5,___L5_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R3(___R1)
   ___SET_R2(___SYM_jazz_2e_platform_2e_syntax_3a_platform_2d_external)
   ___SET_R1(___GLO__23__23_interaction_2d_cte)
   ___SET_R0(___LBL(6))
   ___JUMPGLOSAFE(___SET_NARGS(3),4,___G__23__23_top_2d_cte_2d_add_2d_macro_21_)
___DEF_SLBL(6,___L6_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R2(___LBL(9))
   ___SET_R1(___SYM_jazz_2e_platform_2e_syntax_3a_platform_2d_external)
   ___SET_R0(___LBL(7))
   ___JUMPGLOSAFE(___SET_NARGS(2),8,___G_jazz_3a_register_2d_macro)
___DEF_SLBL(7,___L7_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___POLL(8)
___DEF_SLBL(8,___L8_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___ADJFP(-4)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_SLBL(9,___L9_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___IF_NARGS_EQ(1,___SET_R2(___NUL))
   ___GET_REST(9,1,0,0)
   ___IF(___NOT(___NOTFALSEP(___GLO_jazz_2e_platform_2e_syntax_3a_tracable_3f_)))
   ___GOTO(___L29_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L27_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___SET_R3(___CAR(___R1))
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L25_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___SET_R4(___CDR(___R1))
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_STK(5,___R4)
   ___SET_R1(___R3)
   ___SET_R0(___LBL(10))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_symbol_2d__3e_string)
___DEF_SLBL(10,___L10_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R2(___SUB(0))
   ___SET_R0(___LBL(11))
   ___JUMPPRM(___SET_NARGS(2),___PRM_string_2d_append)
___DEF_SLBL(11,___L11_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R0(___LBL(12))
   ___JUMPPRM(___SET_NARGS(1),___PRM_string_2d__3e_symbol)
___DEF_SLBL(12,___L12_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R2(___CONS(___STK(-4),___STK(-3)))
   ___SET_R2(___CONS(___R2,___STK(-5)))
   ___SET_R2(___CONS(___SYM_c_2d_external,___R2))
   ___SET_R3(___CONS(___R1,___CNS(0)))
   ___SET_R3(___CONS(___SYM_apply,___R3))
   ___BEGIN_ALLOC_LIST(2UL,___STK(-4))
   ___ADD_LIST_ELEM(1,___SYM_quote)
   ___END_ALLOC_LIST(2)
   ___SET_R4(___GET_LIST(2))
   ___SET_R4(___CONS(___R4,___CNS(1)))
   ___SET_R4(___CONS(___CNS(2),___R4))
   ___BEGIN_ALLOC_LIST(3UL,___R4)
   ___ADD_LIST_ELEM(1,___CNS(3))
   ___ADD_LIST_ELEM(2,___SYM_when)
   ___END_ALLOC_LIST(3)
   ___SET_R4(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(4UL,___R3)
   ___ADD_LIST_ELEM(1,___R4)
   ___ADD_LIST_ELEM(2,___SYM_rest)
   ___ADD_LIST_ELEM(3,___SYM_lambda)
   ___END_ALLOC_LIST(4)
   ___SET_R3(___GET_LIST(4))
   ___BEGIN_ALLOC_LIST(3UL,___R3)
   ___ADD_LIST_ELEM(1,___STK(-4))
   ___ADD_LIST_ELEM(2,___SYM_set_21_)
   ___END_ALLOC_LIST(3)
   ___SET_R3(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(3UL,___STK(-4))
   ___ADD_LIST_ELEM(1,___R1)
   ___ADD_LIST_ELEM(2,___SYM_definition)
   ___END_ALLOC_LIST(3)
   ___SET_R4(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(4UL,___R3)
   ___ADD_LIST_ELEM(1,___R4)
   ___ADD_LIST_ELEM(2,___R2)
   ___ADD_LIST_ELEM(3,___SYM_begin)
   ___END_ALLOC_LIST(4)
   ___SET_R2(___GET_LIST(4))
   ___SET_R1(___R2)
   ___ADJFP(-7)
   ___CHECK_HEAP(13,4096)
___DEF_SLBL(13,___L13_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___ADJFP(-1)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L25_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R0(___LBL(14))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_cdr)
___DEF_SLBL(14,___L14_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L26_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___GOTO(___L26_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L27_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R0(___LBL(15))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_car)
___DEF_SLBL(15,___L15_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L28_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___GOTO(___L28_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L29_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R3(___CONS(___R1,___R2))
   ___SET_R3(___CONS(___SYM_c_2d_external,___R3))
   ___SET_R1(___R3)
   ___CHECK_HEAP(16,4096)
___DEF_SLBL(16,___L16_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___JUMPPRM(___NOTHING,___R0)
___DEF_SLBL(17,___L17_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___IF_NARGS_EQ(1,___SET_R2(___NUL))
   ___GET_REST(17,1,0,0)
   ___IF(___NOT(___NOTFALSEP(___GLO_jazz_2e_platform_2e_syntax_3a_tracable_3f_)))
   ___GOTO(___L34_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L32_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___SET_R3(___CAR(___R1))
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L30_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___END_IF
   ___SET_R4(___CDR(___R1))
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_STK(5,___R4)
   ___SET_R1(___R3)
   ___SET_R0(___LBL(18))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_symbol_2d__3e_string)
___DEF_SLBL(18,___L18_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R2(___SUB(0))
   ___SET_R0(___LBL(19))
   ___JUMPPRM(___SET_NARGS(2),___PRM_string_2d_append)
___DEF_SLBL(19,___L19_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R0(___LBL(20))
   ___JUMPPRM(___SET_NARGS(1),___PRM_string_2d__3e_symbol)
___DEF_SLBL(20,___L20_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R2(___CONS(___STK(-4),___STK(-3)))
   ___SET_R2(___CONS(___R2,___STK(-5)))
   ___SET_R2(___CONS(___SYM_c_2d_external,___R2))
   ___SET_R3(___CONS(___R1,___CNS(4)))
   ___SET_R3(___CONS(___SYM_apply,___R3))
   ___BEGIN_ALLOC_LIST(2UL,___STK(-4))
   ___ADD_LIST_ELEM(1,___SYM_quote)
   ___END_ALLOC_LIST(2)
   ___SET_R4(___GET_LIST(2))
   ___SET_R4(___CONS(___R4,___CNS(5)))
   ___SET_R4(___CONS(___CNS(6),___R4))
   ___BEGIN_ALLOC_LIST(3UL,___R4)
   ___ADD_LIST_ELEM(1,___CNS(7))
   ___ADD_LIST_ELEM(2,___SYM_when)
   ___END_ALLOC_LIST(3)
   ___SET_R4(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(4UL,___R3)
   ___ADD_LIST_ELEM(1,___R4)
   ___ADD_LIST_ELEM(2,___SYM_rest)
   ___ADD_LIST_ELEM(3,___SYM_lambda)
   ___END_ALLOC_LIST(4)
   ___SET_R3(___GET_LIST(4))
   ___BEGIN_ALLOC_LIST(3UL,___R3)
   ___ADD_LIST_ELEM(1,___STK(-4))
   ___ADD_LIST_ELEM(2,___SYM_set_21_)
   ___END_ALLOC_LIST(3)
   ___SET_R3(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(3UL,___STK(-4))
   ___ADD_LIST_ELEM(1,___R1)
   ___ADD_LIST_ELEM(2,___SYM_definition)
   ___END_ALLOC_LIST(3)
   ___SET_R4(___GET_LIST(3))
   ___BEGIN_ALLOC_LIST(4UL,___R3)
   ___ADD_LIST_ELEM(1,___R4)
   ___ADD_LIST_ELEM(2,___R2)
   ___ADD_LIST_ELEM(3,___SYM_begin)
   ___END_ALLOC_LIST(4)
   ___SET_R2(___GET_LIST(4))
   ___SET_R1(___R2)
   ___ADJFP(-7)
   ___CHECK_HEAP(21,4096)
___DEF_SLBL(21,___L21_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___ADJFP(-1)
   ___JUMPPRM(___NOTHING,___STK(1))
___DEF_GLBL(___L30_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R0(___LBL(22))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_cdr)
___DEF_SLBL(22,___L22_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L31_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___GOTO(___L31_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L32_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R0(___LBL(23))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(1),___PRM_car)
___DEF_SLBL(23,___L23_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L33_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___GOTO(___L33_bin_3a_jazz_2e_platform_2e_syntax_23_)
___DEF_GLBL(___L34_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___SET_R3(___CONS(___R1,___R2))
   ___SET_R3(___CONS(___SYM_c_2d_external,___R3))
   ___SET_R1(___R3)
   ___CHECK_HEAP(24,4096)
___DEF_SLBL(24,___L24_bin_3a_jazz_2e_platform_2e_syntax_23_)
   ___JUMPPRM(___NOTHING,___R0)
___END_P_SW
___END_P_COD

___END_M_SW
___END_M_COD

___BEGIN_LBL
 ___DEF_LBL_INTRO(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,"bin:jazz.platform.syntax#",___REF_SUB(1)
,25,0)
,___DEF_LBL_PROC(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,0,-1)
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,4,0,0x3f1L))
,___DEF_LBL_PROC(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,2,-1)
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,1,0,0x3f1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_PROC(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,2,-1)
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,1,0,0x3f1L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_bin_3a_jazz_2e_platform_2e_syntax_23_,___IFD(___RETI,0,0,0x3fL))
___END_LBL

___BEGIN_MOD_PRM
___DEF_MOD_PRM(0,___G_bin_3a_jazz_2e_platform_2e_syntax_23_,1)
___END_MOD_PRM

___BEGIN_MOD_C_INIT
___END_MOD_C_INIT

___BEGIN_MOD_GLO
___DEF_MOD_GLO(0,___G_bin_3a_jazz_2e_platform_2e_syntax_23_,1)
___END_MOD_GLO

___BEGIN_MOD_SYM_KEY
___DEF_MOD_SYM(0,___S_apply,"apply")
___DEF_MOD_SYM(1,___S_begin,"begin")
___DEF_MOD_SYM(2,___S_bin_3a_jazz_2e_platform_2e_syntax,"bin:jazz.platform.syntax")
___DEF_MOD_SYM(3,___S_c_2d_external,"c-external")
___DEF_MOD_SYM(4,___S_definition,"definition")
___DEF_MOD_SYM(5,___S_foundation_2e_dialect,"foundation.dialect")
___DEF_MOD_SYM(6,___S_jazz,"jazz")
___DEF_MOD_SYM(7,___S_jazz_2e_platform_2e_syntax,"jazz.platform.syntax")
___DEF_MOD_SYM(8,___S_jazz_2e_platform_2e_syntax_3a_platform_2d_external,"jazz.platform.syntax:platform-external")

___DEF_MOD_SYM(9,___S_lambda,"lambda")
___DEF_MOD_SYM(10,___S_params,"params")
___DEF_MOD_SYM(11,___S_public,"public")
___DEF_MOD_SYM(12,___S_quote,"quote")
___DEF_MOD_SYM(13,___S_rest,"rest")
___DEF_MOD_SYM(14,___S_s_2d_name,"s-name")
___DEF_MOD_SYM(15,___S_set_21_,"set!")
___DEF_MOD_SYM(16,___S_signature,"signature")
___DEF_MOD_SYM(17,___S_trace_2d_platform,"trace-platform")
___DEF_MOD_SYM(18,___S_trace_2d_platform_3f_,"trace-platform?")
___DEF_MOD_SYM(19,___S_when,"when")
___END_MOD_SYM_KEY

#endif
